{\rtf1\ansi\ansicpg1252\cocoartf2868
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Roman;\f1\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 This XML file does not appear to have any style information associated with it. The document tree is shown below.\
\pard\pardeftab720\partightenfactor0

\f1\fs26 \cf0 <xsd:schema\'a0xmlns:epcis="urn:epcglobal:epcis:xsd:1"\'a0xmlns:sbdh="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"\'a0xmlns:epcglobal="urn:epcglobal:xsd:1"\'a0xmlns:xsd="http://www.w3.org/2001/XMLSchema"\'a0targetNamespace="urn:epcglobal:epcis:xsd:1"\'a0elementFormDefault="unqualified"\'a0attributeFormDefault="unqualified"\'a0version="1.2">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\
<epcglobal:copyright>Copyright (C) 2006-2016 GS1 AISBL, All Rights Reserved.</epcglobal:copyright>\
<epcglobal:disclaimer>\'a0THIS DOCUMENT IS PROVIDED \'93AS IS\'94 WITH NO WARRANTIES WHATSOEVER, INCLUDING ANY WARRANTY OF MERCHANTABILITY, NONINFRINGMENT, FITNESS FOR PARTICULAR PURPOSE, OR ANY WARRANTY OTHER WISE ARISING OUT OF THIS SPECIFICATION. GS1 disclaims all liability for any damages arising from use or misuse of this Standard, whether special, indirect, consequential, or compensatory damages, and including liability for infringement of any intellectual property rights, relating to use of information in or reliance upon this document. GS1 retains the right to make changes to this document at any time, without notice. GS1 makes no warranty for the use of this document and assumes no responsibility for any errors which may appear in the document, nor does it make a commitment to update the information contained herein.\'a0</epcglobal:disclaimer>\
<epcglobal:specification>EPC INFORMATION SERVICE (EPCIS) Version 1.2</epcglobal:specification>\
</xsd:documentation>\
</xsd:annotation>\
<xsd:import\'a0namespace="urn:epcglobal:xsd:1"\'a0schemaLocation="./EPCglobal.xsd"/>\
<xsd:import\'a0namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"\'a0schemaLocation="./StandardBusinessDocumentHeader.xsd"/>\
<!--  EPCIS CORE ELEMENTS  -->\
<xsd:element\'a0name="EPCISDocument"\'a0type="epcis:EPCISDocumentType"/>\
<xsd:complexType\'a0name="EPCISDocumentType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0document that contains a Header and a Body.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:complexContent>\
<xsd:extension\'a0base="epcglobal:Document">\
<xsd:sequence>\
<xsd:element\'a0name="EPCISHeader"\'a0type="epcis:EPCISHeaderType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="EPCISBody"\'a0type="epcis:EPCISBodyType"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISDocumentExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISDocumentExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISHeaderType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0specific header(s) including the Standard Business Document Header.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:sequence>\
<xsd:element\'a0ref="sbdh:StandardBusinessDocumentHeader"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISHeaderExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISHeaderExtensionType">\
<xsd:sequence>\
<xsd:element\'a0name="EPCISMasterData"\'a0type="epcis:EPCISMasterDataType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISHeaderExtension2Type"\'a0minOccurs="0"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISHeaderExtension2Type">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  Since 1.2  -->\
<xsd:complexType\'a0name="EPCISMasterDataType">\
<xsd:sequence>\
<xsd:element\'a0name="VocabularyList"\'a0type="epcis:VocabularyListType"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISMasterDataExtensionType"/>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISMasterDataExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<!--  MasterData CORE ELEMENT TYPES  -->\
<xsd:complexType\'a0name="VocabularyListType">\
<xsd:sequence>\
<xsd:element\'a0name="Vocabulary"\'a0type="epcis:VocabularyType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:complexType\'a0name="VocabularyType">\
<xsd:sequence>\
<xsd:element\'a0name="VocabularyElementList"\'a0type="epcis:VocabularyElementListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:VocabularyExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:attribute\'a0name="type"\'a0type="xsd:anyURI"\'a0use="required"/>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="VocabularyElementListType">\
<xsd:sequence>\
<xsd:element\'a0name="VocabularyElement"\'a0type="epcis:VocabularyElementType"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<!--  Implementations SHALL treat a <children list containing zero elements\
       in the same way as if the <children> element were omitted altogether.\
   -->\
<xsd:complexType\'a0name="VocabularyElementType">\
<xsd:sequence>\
<xsd:element\'a0name="attribute"\'a0type="epcis:AttributeType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
<xsd:element\'a0name="children"\'a0type="epcis:IDListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:VocabularyElementExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:attribute\'a0name="id"\'a0type="xsd:anyURI"\'a0use="required"/>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="AttributeType">\
<xsd:complexContent\'a0mixed="true">\
<xsd:extension\'a0base="xsd:anyType">\
<xsd:attribute\'a0name="id"\'a0type="xsd:anyURI"\'a0use="required"/>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<xsd:complexType\'a0name="IDListType">\
<xsd:sequence>\
<xsd:element\'a0name="id"\'a0type="xsd:anyURI"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="VocabularyExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="VocabularyElementExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISBodyType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0specific body that contains EPCIS related Events.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:sequence>\
<xsd:element\'a0name="EventList"\'a0type="epcis:EventListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISBodyExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISBodyExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  EPCIS CORE ELEMENT TYPES  -->\
<xsd:complexType\'a0name="EventListType">\
<xsd:choice\'a0minOccurs="0"\'a0maxOccurs="unbounded">\
<xsd:element\'a0name="ObjectEvent"\'a0type="epcis:ObjectEventType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
<xsd:element\'a0name="AggregationEvent"\'a0type="epcis:AggregationEventType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
<xsd:element\'a0name="QuantityEvent"\'a0type="epcis:QuantityEventType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
<xsd:element\'a0name="TransactionEvent"\'a0type="epcis:TransactionEventType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISEventListExtensionType"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"/>\
</xsd:choice>\
<!--  Note: the use of "unbounded" in both the xsd:choice element\
                    and the enclosed xsd:element elements is, strictly speaking,\
                    redundant. However, this was found to avoid problems with\
                    certain XML processing tools, and so is retained here.\
                 -->\
</xsd:complexType>\
<!--  Modified in 1.1  -->\
<xsd:complexType\'a0name="EPCISEventListExtensionType">\
<xsd:choice>\
<xsd:element\'a0name="TransformationEvent"\'a0type="epcis:TransformationEventType"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISEventListExtension2Type"/>\
</xsd:choice>\
</xsd:complexType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="EPCISEventListExtension2Type">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCListType">\
<xsd:sequence>\
<xsd:element\'a0name="epc"\'a0type="epcglobal:EPC"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:simpleType\'a0name="ActionType">\
<xsd:restriction\'a0base="xsd:string">\
<xsd:enumeration\'a0value="ADD"/>\
<xsd:enumeration\'a0value="OBSERVE"/>\
<xsd:enumeration\'a0value="DELETE"/>\
</xsd:restriction>\
</xsd:simpleType>\
<xsd:simpleType\'a0name="ParentIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Standard Vocabulary  -->\
<xsd:simpleType\'a0name="BusinessStepIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Standard Vocabulary  -->\
<xsd:simpleType\'a0name="DispositionIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  User Vocabulary  -->\
<xsd:simpleType\'a0name="EPCClassType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Standard Vocabulary  -->\
<!--  Since 1.1  -->\
<xsd:simpleType\'a0name="UOMType">\
<xsd:restriction\'a0base="xsd:string"/>\
</xsd:simpleType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="QuantityElementType">\
<xsd:sequence>\
<xsd:element\'a0name="epcClass"\'a0type="epcis:EPCClassType"/>\
<xsd:sequence\'a0minOccurs="0">\
<xsd:element\'a0name="quantity"\'a0type="xsd:decimal"/>\
<xsd:element\'a0name="uom"\'a0type="epcis:UOMType"\'a0minOccurs="0"/>\
</xsd:sequence>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:complexType\'a0name="QuantityListType">\
<xsd:sequence>\
<xsd:element\'a0name="quantityElement"\'a0type="epcis:QuantityElementType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<!--  User Vocabulary  -->\
<xsd:simpleType\'a0name="ReadPointIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<xsd:complexType\'a0name="ReadPointType">\
<xsd:sequence>\
<xsd:element\'a0name="id"\'a0type="epcis:ReadPointIDType"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:ReadPointExtensionType"\'a0minOccurs="0"/>\
<!--  The wildcard below provides the extension mechanism described in Section 9.4  -->\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:complexType\'a0name="ReadPointExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  User Vocabulary  -->\
<xsd:simpleType\'a0name="BusinessLocationIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<xsd:complexType\'a0name="BusinessLocationType">\
<xsd:sequence>\
<xsd:element\'a0name="id"\'a0type="epcis:BusinessLocationIDType"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:BusinessLocationExtensionType"\'a0minOccurs="0"/>\
<!--  The wildcard below provides the extension mechanism described in Section 9.4  -->\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:complexType\'a0name="BusinessLocationExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  User Vocabulary  -->\
<xsd:simpleType\'a0name="BusinessTransactionIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Standard Vocabulary  -->\
<xsd:simpleType\'a0name="BusinessTransactionTypeIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<xsd:complexType\'a0name="BusinessTransactionType">\
<xsd:simpleContent>\
<xsd:extension\'a0base="epcis:BusinessTransactionIDType">\
<xsd:attribute\'a0name="type"\'a0type="epcis:BusinessTransactionTypeIDType"\'a0use="optional"/>\
</xsd:extension>\
</xsd:simpleContent>\
</xsd:complexType>\
<xsd:complexType\'a0name="BusinessTransactionListType">\
<xsd:sequence>\
<xsd:element\'a0name="bizTransaction"\'a0type="epcis:BusinessTransactionType"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<!--  User Vocabulary  -->\
<!--  Since 1.1  -->\
<xsd:simpleType\'a0name="SourceDestIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Standard Vocabulary  -->\
<!--  Since 1.1  -->\
<xsd:simpleType\'a0name="SourceDestTypeIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="SourceDestType">\
<xsd:simpleContent>\
<xsd:extension\'a0base="epcis:SourceDestIDType">\
<xsd:attribute\'a0name="type"\'a0type="epcis:SourceDestTypeIDType"\'a0use="required"/>\
</xsd:extension>\
</xsd:simpleContent>\
</xsd:complexType>\
<xsd:complexType\'a0name="SourceListType">\
<xsd:sequence>\
<xsd:element\'a0name="source"\'a0type="epcis:SourceDestType"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<xsd:complexType\'a0name="DestinationListType">\
<xsd:sequence>\
<xsd:element\'a0name="destination"\'a0type="epcis:SourceDestType"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<!--  User Vocabulary  -->\
<!--  Since 1.1  -->\
<xsd:simpleType\'a0name="TransformationIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="ILMDType">\
<xsd:sequence>\
<xsd:element\'a0name="extension"\'a0type="epcis:ILMDExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="ILMDExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  User Vocabulary  -->\
<!--  Since 1.2  -->\
<xsd:simpleType\'a0name="EventIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Standard Vocabulary  -->\
<!--  Since 1.2  -->\
<xsd:simpleType\'a0name="ErrorReasonIDType">\
<xsd:restriction\'a0base="xsd:anyURI"/>\
</xsd:simpleType>\
<!--  Since 1.2  -->\
<xsd:complexType\'a0name="CorrectiveEventIDsType">\
<xsd:sequence>\
<xsd:element\'a0name="correctiveEventID"\'a0type="epcis:EventIDType"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
</xsd:complexType>\
<!--  Since 1.2  -->\
<xsd:complexType\'a0name="ErrorDeclarationType">\
<xsd:sequence>\
<xsd:element\'a0name="declarationTime"\'a0type="xsd:dateTime"/>\
<xsd:element\'a0name="reason"\'a0type="epcis:ErrorReasonIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="correctiveEventIDs"\'a0type="epcis:CorrectiveEventIDsType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:ErrorDeclarationExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="ErrorDeclarationExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  items listed alphabetically by name  -->\
<!--  Some element types accommodate extensibility in the manner of\
        "Versioning XML Vocabularies" by David Orchard (see\
        http://www.xml.com/pub/a/2003/12/03/versioning.html).\
\
        In this approach, an optional <extension> element is defined\
        for each extensible element type, where an <extension> element\
        may contain future elements defined in the target namespace.\
\
        In addition to the optional <extension> element, extensible element\
        types are declared with a final xsd:any wildcard to accommodate\
        future elements defined by third parties (as denoted by the ##other\
        namespace).\
\
        Finally, the xsd:anyAttribute facility is used to allow arbitrary\
        attributes to be added to extensible element types.  -->\
<xsd:complexType\'a0name="EPCISEventType"\'a0abstract="true">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0base type for all EPCIS events.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:sequence>\
<xsd:element\'a0name="eventTime"\'a0type="xsd:dateTime"/>\
<xsd:element\'a0name="recordTime"\'a0type="xsd:dateTime"\'a0minOccurs="0"/>\
<xsd:element\'a0name="eventTimeZoneOffset"\'a0type="xsd:string"/>\
<xsd:element\'a0name="baseExtension"\'a0type="epcis:EPCISEventExtensionType"\'a0minOccurs="0"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISEventExtensionType">\
<xsd:sequence>\
<xsd:element\'a0name="eventID"\'a0type="epcis:EventIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="errorDeclaration"\'a0type="epcis:ErrorDeclarationType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:EPCISEventExtension2Type"\'a0minOccurs="0"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="EPCISEventExtension2Type">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="ObjectEventType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0Object Event captures information about an event pertaining to one or more objects identified by EPCs.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:complexContent>\
<xsd:extension\'a0base="epcis:EPCISEventType">\
<xsd:sequence>\
<xsd:element\'a0name="epcList"\'a0type="epcis:EPCListType"/>\
<xsd:element\'a0name="action"\'a0type="epcis:ActionType"/>\
<xsd:element\'a0name="bizStep"\'a0type="epcis:BusinessStepIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="disposition"\'a0type="epcis:DispositionIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="readPoint"\'a0type="epcis:ReadPointType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizLocation"\'a0type="epcis:BusinessLocationType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizTransactionList"\'a0type="epcis:BusinessTransactionListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:ObjectEventExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<!--  Modified in 1.1  -->\
<xsd:complexType\'a0name="ObjectEventExtensionType">\
<xsd:sequence>\
<xsd:element\'a0name="quantityList"\'a0type="epcis:QuantityListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="sourceList"\'a0type="epcis:SourceListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="destinationList"\'a0type="epcis:DestinationListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="ilmd"\'a0type="epcis:ILMDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:ObjectEventExtension2Type"\'a0minOccurs="0"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="ObjectEventExtension2Type">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="AggregationEventType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0Aggregation Event captures an event that applies to objects that have a physical association with one another.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:complexContent>\
<xsd:extension\'a0base="epcis:EPCISEventType">\
<xsd:sequence>\
<xsd:element\'a0name="parentID"\'a0type="epcis:ParentIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="childEPCs"\'a0type="epcis:EPCListType"/>\
<xsd:element\'a0name="action"\'a0type="epcis:ActionType"/>\
<xsd:element\'a0name="bizStep"\'a0type="epcis:BusinessStepIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="disposition"\'a0type="epcis:DispositionIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="readPoint"\'a0type="epcis:ReadPointType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizLocation"\'a0type="epcis:BusinessLocationType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizTransactionList"\'a0type="epcis:BusinessTransactionListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:AggregationEventExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<!--  Modified in 1.1  -->\
<xsd:complexType\'a0name="AggregationEventExtensionType">\
<xsd:sequence>\
<xsd:element\'a0name="childQuantityList"\'a0type="epcis:QuantityListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="sourceList"\'a0type="epcis:SourceListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="destinationList"\'a0type="epcis:DestinationListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:AggregationEventExtension2Type"\'a0minOccurs="0"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="AggregationEventExtension2Type">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="QuantityEventType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0Quantity Event captures an event that takes place with respect to a specified quantity of object class.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:complexContent>\
<xsd:extension\'a0base="epcis:EPCISEventType">\
<xsd:sequence>\
<xsd:element\'a0name="epcClass"\'a0type="epcis:EPCClassType"/>\
<xsd:element\'a0name="quantity"\'a0type="xsd:int"/>\
<xsd:element\'a0name="bizStep"\'a0type="epcis:BusinessStepIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="disposition"\'a0type="epcis:DispositionIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="readPoint"\'a0type="epcis:ReadPointType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizLocation"\'a0type="epcis:BusinessLocationType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizTransactionList"\'a0type="epcis:BusinessTransactionListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:QuantityEventExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<xsd:complexType\'a0name="QuantityEventExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<xsd:complexType\'a0name="TransactionEventType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0Transaction Event describes the association or disassociation of physical objects to one or more business transactions.\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:complexContent>\
<xsd:extension\'a0base="epcis:EPCISEventType">\
<xsd:sequence>\
<xsd:element\'a0name="bizTransactionList"\'a0type="epcis:BusinessTransactionListType"/>\
<xsd:element\'a0name="parentID"\'a0type="epcis:ParentIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="epcList"\'a0type="epcis:EPCListType"/>\
<xsd:element\'a0name="action"\'a0type="epcis:ActionType"/>\
<xsd:element\'a0name="bizStep"\'a0type="epcis:BusinessStepIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="disposition"\'a0type="epcis:DispositionIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="readPoint"\'a0type="epcis:ReadPointType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizLocation"\'a0type="epcis:BusinessLocationType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:TransactionEventExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<!--  Modified in 1.1  -->\
<xsd:complexType\'a0name="TransactionEventExtensionType">\
<xsd:sequence>\
<xsd:element\'a0name="quantityList"\'a0type="epcis:QuantityListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="sourceList"\'a0type="epcis:SourceListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="destinationList"\'a0type="epcis:DestinationListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:TransactionEventExtension2Type"\'a0minOccurs="0"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="TransactionEventExtension2Type">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="TransformationEventType">\
<xsd:annotation>\
<xsd:documentation\'a0xml:lang="en">\'a0Transformation Event captures an event in which inputs are consumed and outputs are produced\'a0</xsd:documentation>\
</xsd:annotation>\
<xsd:complexContent>\
<xsd:extension\'a0base="epcis:EPCISEventType">\
<xsd:sequence>\
<xsd:element\'a0name="inputEPCList"\'a0type="epcis:EPCListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="inputQuantityList"\'a0type="epcis:QuantityListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="outputEPCList"\'a0type="epcis:EPCListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="outputQuantityList"\'a0type="epcis:QuantityListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="transformationID"\'a0type="epcis:TransformationIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizStep"\'a0type="epcis:BusinessStepIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="disposition"\'a0type="epcis:DispositionIDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="readPoint"\'a0type="epcis:ReadPointType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizLocation"\'a0type="epcis:BusinessLocationType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="bizTransactionList"\'a0type="epcis:BusinessTransactionListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="sourceList"\'a0type="epcis:SourceListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="destinationList"\'a0type="epcis:DestinationListType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="ilmd"\'a0type="epcis:ILMDType"\'a0minOccurs="0"/>\
<xsd:element\'a0name="extension"\'a0type="epcis:TransformationEventExtensionType"\'a0minOccurs="0"/>\
<xsd:any\'a0namespace="##other"\'a0processContents="lax"\'a0minOccurs="0"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:extension>\
</xsd:complexContent>\
</xsd:complexType>\
<!--  Since 1.1  -->\
<xsd:complexType\'a0name="TransformationEventExtensionType">\
<xsd:sequence>\
<xsd:any\'a0namespace="##local"\'a0processContents="lax"\'a0maxOccurs="unbounded"/>\
</xsd:sequence>\
<xsd:anyAttribute\'a0processContents="lax"/>\
</xsd:complexType>\
</xsd:schema>\
}