spring:
  application:
    name: epcis-event-handler

  datasource:
    url: jdbc:postgresql://localhost:5432/kamiljasinski
    username: kamiljasinski
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

epcis:
  output:
    directory: ./output/events
  schema:
    path: classpath:xsd/EPCglobal-epcis-1_2.xsd
