package com.canda.epcis.infrastructure.persistence.subscription;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.OffsetDateTime;

/*
 * DDL (V5__phase3_tables.sql):
 *
 * CREATE TABLE epcis_subscription (
 *     id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     subscription_id   VARCHAR(100) NOT NULL UNIQUE,
 *     target_system     VARCHAR(100) NOT NULL,
 *     callback_url      VARCHAR(500) NOT NULL,
 *     auth_type         VARCHAR(20)  NOT NULL DEFAULT 'NONE',
 *     auth_token        VARCHAR(500),
 *     event_types       VARCHAR(500),
 *     biz_steps         TEXT,
 *     dispositions      TEXT,
 *     biz_locations     TEXT,
 *     read_points       TEXT,
 *     active            BOOLEAN      NOT NULL DEFAULT true,
 *     created_at        TIMESTAMPTZ  NOT NULL,
 *     last_triggered_at TIMESTAMPTZ
 * );
 *
 * Hinweis: auth_token wird derzeit im Klartext gespeichert.
 * Verschlüsselung (AES/KMS) ist für Phase 4 vorgesehen.
 */
@Entity
@Table(name = "epcis_subscription")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubscriptionEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Fachliche ID, z.B. "HALO-GENERAL", "MULE-RSTO". Muss eindeutig sein. */
    @Column(name = "subscription_id", nullable = false, unique = true, length = 100)
    private String subscriptionId;

    /** Zielsystem-Name, z.B. "HALO", "MULE", "ITEMOPTIX". */
    @Column(name = "target_system", nullable = false, length = 100)
    private String targetSystem;

    /** HTTP-Endpunkt des Subscribers. */
    @Column(name = "callback_url", nullable = false, length = 500)
    private String callbackUrl;

    /** Authentifizierungstyp: NONE / BEARER / BASIC. */
    @Column(name = "auth_type", nullable = false, length = 20)
    private String authType;

    /** Bearer Token (Klartext — Phase 4: Verschlüsselung). */
    @Column(name = "auth_token", length = 500)
    private String authToken;

    /** Komma-separierte Event-Typen: "ObjectEvent,AggregationEvent". Null = alle. */
    @Column(name = "event_types", length = 500)
    private String eventTypes;

    /** Komma-separierte bizStep Short-Names: "receiving,shipping". Null = alle. */
    @Column(name = "biz_steps", columnDefinition = "TEXT")
    private String bizSteps;

    /** Komma-separierte disposition Short-Names. Null = alle. */
    @Column(name = "dispositions", columnDefinition = "TEXT")
    private String dispositions;

    /** Komma-separierte SGLN-URIs für bizLocation-Prefix-Match. Null = alle. */
    @Column(name = "biz_locations", columnDefinition = "TEXT")
    private String bizLocations;

    /** Komma-separierte SGLN-URIs für readPoint-Prefix-Match. Null = alle. */
    @Column(name = "read_points", columnDefinition = "TEXT")
    private String readPoints;

    @Column(name = "active", nullable = false)
    private boolean active;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "last_triggered_at")
    private OffsetDateTime lastTriggeredAt;
}
