package com.canda.epcis.infrastructure.persistence.outbox;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.OffsetDateTime;

/*
 * DDL (V5__phase3_tables.sql):
 *
 * CREATE TABLE outbox_message (
 *     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     message_id     VARCHAR(36)  NOT NULL UNIQUE,
 *     message_type   VARCHAR(100) NOT NULL,
 *     target_system  VARCHAR(50)  NOT NULL,
 *     payload        TEXT         NOT NULL,
 *     status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
 *     created_at     TIMESTAMPTZ  NOT NULL,
 *     sent_at        TIMESTAMPTZ,
 *     retry_count    INT          NOT NULL DEFAULT 0,
 *     last_error     TEXT,
 *     correlation_id VARCHAR(255)
 * );
 */
@Entity
@Table(name = "outbox_message")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OutboxEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** UUID — Idempotenz-Schlüssel. Wird beim Anlegen gesetzt, nie geändert. */
    @Column(name = "message_id", nullable = false, unique = true, length = 36)
    private String messageId;

    /** Nachrichtentyp: "RFID_INVENTORY", "RFID_SHIPPING", "RFID_ARRIVAL",
     *  "GOODS_RECEIPT", "RFID_SALES", "RFID_RETURNS", "TROLLEY_SSCCS", "SUBSCRIPTION" */
    @Column(name = "message_type", nullable = false, length = 100)
    private String messageType;

    /** Zielsystem: "GSPM", "ERP", "DWH", "EWM", "SUBSCRIPTION" */
    @Column(name = "target_system", nullable = false, length = 50)
    private String targetSystem;

    /** JSON-Payload — vollständige Nachricht für das Zielsystem. */
    @Column(name = "payload", nullable = false, columnDefinition = "TEXT")
    private String payload;

    /** PENDING → SENT oder FAILED */
    @Column(name = "status", nullable = false, length = 20)
    private String status;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "sent_at")
    private OffsetDateTime sentAt;

    @Column(name = "retry_count", nullable = false)
    private int retryCount;

    @Column(name = "last_error", columnDefinition = "TEXT")
    private String lastError;

    /** Für Subscriptions: subscription_id. Für Shipping: SSCC-URN. Für Events: eventId. */
    @Column(name = "correlation_id", length = 255)
    private String correlationId;
}
