package com.canda.epcis.infrastructure.persistence.audit;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

/**
 * Reconciliation-Tabelle für Parallelbetrieb EECC ↔ neues System.
 * Eine Zeile pro Capture-Session.
 *
 * SQL (Flyway V3):
 *
 * CREATE TABLE capture_audit (
 *     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     session_id     VARCHAR(36)  NOT NULL UNIQUE,
 *     source_id      VARCHAR(100) NOT NULL,
 *     received_at    TIMESTAMPTZ  NOT NULL,
 *     total_received INT          NOT NULL DEFAULT 0,
 *     total_accepted INT          NOT NULL DEFAULT 0,
 *     total_filtered INT          NOT NULL DEFAULT 0,
 *     total_dropped  INT          NOT NULL DEFAULT 0,
 *     total_errors   INT          NOT NULL DEFAULT 0
 * );
 *
 * CREATE INDEX idx_capture_audit_source   ON capture_audit(source_id);
 * CREATE INDEX idx_capture_audit_received ON capture_audit(received_at);
 */
@Entity
@Table(name = "capture_audit")
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CaptureAuditEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "session_id", nullable = false, unique = true, length = 36)
    private String sessionId;

    @Column(name = "source_id", nullable = false, length = 100)
    private String sourceId;

    @Column(name = "received_at", nullable = false)
    private OffsetDateTime receivedAt;

    @Column(name = "total_received", nullable = false)
    private int totalReceived;

    @Column(name = "total_accepted", nullable = false)
    private int totalAccepted;

    @Column(name = "total_filtered", nullable = false)
    private int totalFiltered;

    @Column(name = "total_dropped", nullable = false)
    private int totalDropped;

    @Column(name = "total_errors", nullable = false)
    private int totalErrors;
}
