-- V1: Initial EPCIS event store schema (H2-compatible)
CREATE TABLE IF NOT EXISTS epcis_event (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR(50)     NOT NULL,
    event_time  TIMESTAMP WITH TIME ZONE,
    payload     TEXT            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_epcis_event_type ON epcis_event (event_type);
CREATE INDEX IF NOT EXISTS idx_epcis_event_time ON epcis_event (event_time);
