-- V2: Quarantine table (H2-compatible)
CREATE TABLE IF NOT EXISTS epcis_quarantine (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason          VARCHAR(500)    NOT NULL,
    error_code      VARCHAR(100),
    raw_fragment    TEXT            NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_epcis_quarantine_created_at ON epcis_quarantine (created_at);
CREATE INDEX IF NOT EXISTS idx_epcis_quarantine_error_code ON epcis_quarantine (error_code);
