-- V3: Capture Audit table (H2-compatible)
CREATE TABLE IF NOT EXISTS capture_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     VARCHAR(36)  NOT NULL UNIQUE,
    source_id      VARCHAR(100) NOT NULL,
    received_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    total_received INT          NOT NULL DEFAULT 0,
    total_accepted INT          NOT NULL DEFAULT 0,
    total_filtered INT          NOT NULL DEFAULT 0,
    total_dropped  INT          NOT NULL DEFAULT 0,
    total_errors   INT          NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_capture_audit_source   ON capture_audit(source_id);
CREATE INDEX IF NOT EXISTS idx_capture_audit_received ON capture_audit(received_at);
