-- V4: Inventory Service tables (H2-compatible)

CREATE TABLE IF NOT EXISTS epc_state (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epc_urn                      VARCHAR(255) NOT NULL,
    current_status               VARCHAR(100),
    biz_location                 VARCHAR(255),
    last_event_id                VARCHAR(255),
    last_event_time              TIMESTAMP WITH TIME ZONE,
    sscc                         VARCHAR(255),
    create_date                  TIMESTAMP WITH TIME ZONE NOT NULL,
    update_date                  TIMESTAMP WITH TIME ZONE NOT NULL,
    encoded_at                   TIMESTAMP WITH TIME ZONE,
    in_progress_at               TIMESTAMP WITH TIME ZONE,
    in_transit_at                TIMESTAMP WITH TIME ZONE,
    accessible_for_customer_at   TIMESTAMP WITH TIME ZONE,
    available_not_accessible_at  TIMESTAMP WITH TIME ZONE,
    retired_at                   TIMESTAMP WITH TIME ZONE,
    sold_at                      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_epc_state_epc_urn UNIQUE (epc_urn)
);

CREATE INDEX IF NOT EXISTS idx_epc_state_biz_location ON epc_state (biz_location);
CREATE INDEX IF NOT EXISTS idx_epc_state_sscc         ON epc_state (sscc);
CREATE INDEX IF NOT EXISTS idx_epc_state_status       ON epc_state (current_status);

CREATE TABLE IF NOT EXISTS sscc_content (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sscc_urn     VARCHAR(255) NOT NULL,
    child_epc    VARCHAR(255) NOT NULL,
    biz_location VARCHAR(255),
    added_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_sscc_content_sscc_child UNIQUE (sscc_urn, child_epc)
);

CREATE INDEX IF NOT EXISTS idx_sscc_content_sscc      ON sscc_content (sscc_urn);
CREATE INDEX IF NOT EXISTS idx_sscc_content_child_epc ON sscc_content (child_epc);

CREATE TABLE IF NOT EXISTS movement_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epc_urn      VARCHAR(255) NOT NULL,
    event_id     VARCHAR(255) NOT NULL,
    event_type   VARCHAR(50)  NOT NULL,
    action       VARCHAR(20)  NOT NULL,
    biz_step     VARCHAR(255),
    disposition  VARCHAR(255),
    biz_location VARCHAR(255),
    read_point   VARCHAR(255),
    event_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_movement_history_epc_event UNIQUE (epc_urn, event_id)
);

CREATE INDEX IF NOT EXISTS idx_movement_history_epc_time     ON movement_history (epc_urn, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_movement_history_biz_location ON movement_history (biz_location);
