-- V5: Phase 3 Downstream Integration tables (H2-compatible)

CREATE TABLE IF NOT EXISTS outbox_message (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id     VARCHAR(36)  NOT NULL UNIQUE,
    message_type   VARCHAR(100) NOT NULL,
    target_system  VARCHAR(50)  NOT NULL,
    payload        TEXT         NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at        TIMESTAMP WITH TIME ZONE,
    retry_count    INT          NOT NULL DEFAULT 0,
    last_error     TEXT,
    correlation_id VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_outbox_status_target ON outbox_message(status, target_system);
CREATE INDEX IF NOT EXISTS idx_outbox_created       ON outbox_message(created_at);

CREATE TABLE IF NOT EXISTS epcis_subscription (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id   VARCHAR(100) NOT NULL UNIQUE,
    target_system     VARCHAR(100) NOT NULL,
    callback_url      VARCHAR(500) NOT NULL,
    auth_type         VARCHAR(20)  NOT NULL DEFAULT 'NONE',
    auth_token        VARCHAR(500),
    event_types       VARCHAR(500),
    biz_steps         TEXT,
    dispositions      TEXT,
    biz_locations     TEXT,
    read_points       TEXT,
    active            BOOLEAN      NOT NULL DEFAULT true,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    last_triggered_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS inventory_snapshot (
    gtin         VARCHAR(50)  NOT NULL,
    sgln         VARCHAR(255) NOT NULL,
    last_qty     INT          NOT NULL DEFAULT 0,
    last_sent_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (gtin, sgln)
);

CREATE TABLE IF NOT EXISTS shipping_sent (
    sscc             VARCHAR(255) PRIMARY KEY,
    last_destination VARCHAR(255),
    last_sent_at     TIMESTAMP WITH TIME ZONE
);
