-- V6: Phase 4 CBV Vocabulary + CBV Quarantine tables (H2-compatible)

CREATE TABLE IF NOT EXISTS cbv_vocabulary (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocabulary_type VARCHAR(50)  NOT NULL,
    payload         VARCHAR(100) NOT NULL,
    urn_uri         VARCHAR(255) NOT NULL,
    https_uri       VARCHAR(255) NOT NULL,
    deprecated      BOOLEAN      NOT NULL DEFAULT false,
    CONSTRAINT uq_cbv_vocabulary_type_payload UNIQUE (vocabulary_type, payload)
);

CREATE INDEX IF NOT EXISTS idx_cbv_vocabulary_type ON cbv_vocabulary(vocabulary_type);
CREATE INDEX IF NOT EXISTS idx_cbv_urn_uri         ON cbv_vocabulary(urn_uri);

CREATE TABLE IF NOT EXISTS quarantine_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(255),
    event_type      VARCHAR(50),
    source_id       VARCHAR(100),
    reason_code     VARCHAR(100) NOT NULL,
    reason_detail   TEXT,
    raw_payload     TEXT,
    quarantined_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved        BOOLEAN      NOT NULL DEFAULT false,
    resolved_at     TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_quarantine_resolved    ON quarantine_event(resolved);
CREATE INDEX IF NOT EXISTS idx_quarantine_reason_code ON quarantine_event(reason_code);
CREATE INDEX IF NOT EXISTS idx_quarantine_quarantined ON quarantine_event(quarantined_at);
