-- ═══════════════════════════════════════════════════════════════
-- V4 — Inventory Service Tables (Phase 2)
-- ═══════════════════════════════════════════════════════════════

-- EPC State Tabelle (REQ401)
-- Speichert den letzten bekannten Zustand jeder SGTIN.
CREATE TABLE epc_state (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epc_urn                      VARCHAR(255) NOT NULL,
    current_status               VARCHAR(100),
    biz_location                 VARCHAR(255),
    last_event_id                VARCHAR(255),
    last_event_time              TIMESTAMPTZ,
    sscc                         VARCHAR(255),
    create_date                  TIMESTAMPTZ NOT NULL,
    update_date                  TIMESTAMPTZ NOT NULL,
    encoded_at                   TIMESTAMPTZ,
    in_progress_at               TIMESTAMPTZ,
    in_transit_at                TIMESTAMPTZ,
    accessible_for_customer_at   TIMESTAMPTZ,
    available_not_accessible_at  TIMESTAMPTZ,
    retired_at                   TIMESTAMPTZ,
    sold_at                      TIMESTAMPTZ,
    CONSTRAINT uq_epc_state_epc_urn UNIQUE (epc_urn)
);

CREATE INDEX idx_epc_state_biz_location ON epc_state (biz_location);
CREATE INDEX idx_epc_state_sscc         ON epc_state (sscc);
CREATE INDEX idx_epc_state_status       ON epc_state (current_status);

-- ───────────────────────────────────────────────────────────────

-- SSCC Content Tabelle
-- Speichert welche SGTINs aktuell auf welcher SSCC (Palette) sind.
CREATE TABLE sscc_content (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sscc_urn     VARCHAR(255) NOT NULL,
    child_epc    VARCHAR(255) NOT NULL,
    biz_location VARCHAR(255),
    added_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_sscc_content_sscc_child UNIQUE (sscc_urn, child_epc)
);

CREATE INDEX idx_sscc_content_sscc      ON sscc_content (sscc_urn);
CREATE INDEX idx_sscc_content_child_epc ON sscc_content (child_epc);

-- ───────────────────────────────────────────────────────────────

-- Movement History Tabelle
-- Vollständige Bewegungshistorie pro EPC — append-only.
CREATE TABLE movement_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epc_urn      VARCHAR(255) NOT NULL,
    event_id     VARCHAR(255) NOT NULL,
    event_type   VARCHAR(50)  NOT NULL,
    action       VARCHAR(20)  NOT NULL,
    biz_step     VARCHAR(255),
    disposition  VARCHAR(255),
    biz_location VARCHAR(255),
    read_point   VARCHAR(255),
    event_time   TIMESTAMPTZ  NOT NULL,
    recorded_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_movement_history_epc_event UNIQUE (epc_urn, event_id)
);

CREATE INDEX idx_movement_history_epc_time
    ON movement_history (epc_urn, event_time DESC);
CREATE INDEX idx_movement_history_biz_location
    ON movement_history (biz_location);
