-- Phase 4: CBV Vocabulary table + CBV Quarantine table
-- CBV vocabulary is loaded by CbvVocabularyLoader on application startup.
-- quarantine_event holds CBV-violation events (strict-mode only).

-- ─────────────────────────────────────────────────────────────────────────────
-- CBV Vocabulary
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE cbv_vocabulary (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocabulary_type VARCHAR(50)  NOT NULL,
    payload         VARCHAR(100) NOT NULL,
    urn_uri         VARCHAR(255) NOT NULL,
    https_uri       VARCHAR(255) NOT NULL,
    deprecated      BOOLEAN      NOT NULL DEFAULT false,
    CONSTRAINT uq_cbv_vocabulary_type_payload UNIQUE (vocabulary_type, payload)
);

CREATE INDEX idx_cbv_vocabulary_type ON cbv_vocabulary(vocabulary_type);
CREATE INDEX idx_cbv_urn_uri         ON cbv_vocabulary(urn_uri);

-- ─────────────────────────────────────────────────────────────────────────────
-- CBV Quarantine
-- Distinct from epcis_quarantine (structural/parsing failures).
-- This table holds semantic CBV violations when strict-mode=true.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE quarantine_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(255),
    event_type      VARCHAR(50),
    source_id       VARCHAR(100),
    reason_code     VARCHAR(100) NOT NULL,
    reason_detail   TEXT,
    raw_payload     TEXT,
    quarantined_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    resolved        BOOLEAN      NOT NULL DEFAULT false,
    resolved_at     TIMESTAMPTZ
);

CREATE INDEX idx_quarantine_resolved    ON quarantine_event(resolved);
CREATE INDEX idx_quarantine_reason_code ON quarantine_event(reason_code);
CREATE INDEX idx_quarantine_quarantined ON quarantine_event(quarantined_at);
